version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - sh custom_image_scripts.sh
  post_build:
    commands:
      - tag=$(grep -w "deployment_tag" ./manual_deployment_parameters.yaml | awk -F= '{print $2}')
      - env=$(grep -w "environment" ./manual_deployment_parameters.yaml | awk -F= '{print $2}')
      - app=$(grep -w "application" ./manual_deployment_parameters.yaml | awk -F= '{print $2}')
      - cluster=$(grep -w "cluster" ./manual_deployment_parameters.yaml | awk -F= '{print $2}')
      - ecrtag=$(aws ecr describe-images --repository-name=actimize-$env-$app  --image-ids=imageTag=$tag | jq '.imageDetails[0].imageTags[0]' -r)
      - echo $ecrtag
      - cd ~/.aws
      - rm -f /root/.aws/credentials
      - echo Listing aws folder to confirm aws credentials has been removed from the custom Image...
      - ls /root/.aws
artifacts:
    files: imagedefinitions.json
